import "@/styles/globals.css";
import type { Metadata } from "next";
import SideNav from "./_components/SideNav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen w-screen overflow-hidden bg-slate-700">
          <SideNav />
          <main className="flex flex-1 overflow-hidden">{children}</main>
        </div>
      </body>
    </html>
  );
}
